### PR TITLE
Add sarah young key

### PR DESCRIPTION
**Pull request by sarahseewhy**
I have joined GOV.UK and am adding my keys to the Puppet repo.

### CODE REVIEW

**Comment by issyl0** [comment]
The linter says: `modules/users/manifests/sarahyoung.pp - WARNING: missing trailing comma after last element on line 6`.

**Comment by issyl0** [comment]
Also I think your `.gitconfig` is misconfigured - your commit authorship is coming up as `From: Sarah C Y <sarahseewhy@gmail>` and not associating with your GitHub account or your GPG key. It's missing a `.com`, or your GDS email address. 😅

**Comment by sarahseewhy** [comment]
Yikes! I'll fix these tomorrow, thank you for checking it out and pointing out the `.gitconfig`  🙇‍♀

**Comment by issyl0** [comment]
Change-wise, this is looking good. Final thing: could you please squash your commits?

**Comment by sarahseewhy** [comment]
Thanks! I appreciate your help and patience, still learning the GOV.UK ropes a bit 😁.

**Pull request merged**
