### PR TITLE
Allow selectively changing where apps look for rummager

### PR DESCRIPTION
**Pull request by barrucadu**
This is going to be useful as we migrate from rummager to search-api.  When we're happy the data in rummager and search-api is consistent, and that updates are being sent to both apps, we can gradually change which one is used for queries.

---

[Trello card](https://trello.com/c/YTAtoA21/22-add-an-option-to-each-app-which-uses-rummager-to-override-plek)

### CODE REVIEW

**Comment by barrucadu** [comment]
I *think* these are the only apps which use rummager.

The idea is that we'll get the data in rummager and search-api in sync, with updates going to both apps, and then gradually switch the apps over as we gain confidence that it's all working.

Once these apps have all been switched to use search-api, this special configuration can be removed and we'll just update the apps to use `Plek("search-api")`.

**Comment by cbaines** [comment]
I don't quite follow...

What I'm suggesting is applying the configuration in govuk-puppet here for example https://github.com/alphagov/govuk-puppet/blob/master/modules/govuk/manifests/deploy/config.pp#L87-L116

Providing you are going to have all the apps using the same value, that should work similarly, but not require as many changes in govuk-puppet.

**Comment by barrucadu** [comment]
We're planning to roll out the switch to search-api like this:

1. For each app:
    1. Set `override_search_location` for that app
    2. Deploy puppet to staging and run it on the affected nodes
    3. Test app in staging
    4. Deploy puppet to production and run it on the affected nodes
    5. Test app in production
2. Check X-Ray logs for Rummager (dial up the reporting rate if necessary) to make sure nothing is still talking to it
3. Update each app to reference `search-api` directly, instead of `search` or `rummager`
4. Remove this special configuration

So the ability to do this on a per-app basis is important.

The reason we're doing it this way is that it seems less risky.  If we discover a problem only when we hit production, only one app will be busted rather than everything which uses rummager.

**Comment by cbaines** [comment]
> So the ability to do this on a per-app basis is important.

Ok.

**Pull request merged**
