### PR TITLE
Update Specialist Publisher application env

### PR DESCRIPTION
**Pull request by steventux**
Specialist Publisher will use the codebase from Specialist Publisher Rebuild very shortly, so ensure that the same environment is created for both applications to ease deployment.

This means the same ENV variables should be made available and any config from alphagov-deployment should be added to the environment where relevant.

Secrets here https://github.gds/gds/deployment/pull/1103 (this has now been merged)

### CODE REVIEW

**Comment by alexmuller** [comment]
I pushed an additional commit which I think makes the overall set of changes in this pull request much easier to review - feel free to either squash it in or discard it, but it shouldn't be merged with the message as it exists :)

**Comment by steventux** [comment]
@alexmuller: This is the branch I test deployed to integration, it supplied the correct environment vars for specialist-publisher and used the same cookie secret. Would you mind reviewing when you have a moment.

**Comment by alexmuller** [comment]
There are lots of other places where it's worth using the `$app_name` variable from the final commit.

Apart from that this looks good to me :+1:

Nitpick: the first 2 commits could be squashed together.

**Comment by steventux** [comment]
@alexmuller thanks :+1: I've amended

**Pull request merged**
