### PR TITLE
Add new user Pablo Manrubia

### PR DESCRIPTION
**Pull request by pmanrubia**
Add user `pablomanrubia` to the integration environment in the `admins` group.
Access is requested as part of the `Travel Advice Planner` work.

Supersed: #4331 

@gpeng It's been updated with your comments; cc/ @jackscotti 
Thank you

### CODE REVIEW

**Comment by gpeng** [comment]
Looks good to me. :+1:

**Comment by benilovj** [comment]
Pull requests from outside this repo seem to confuse Jenkins (I had a similar problem with https://github.com/alphagov/govuk-puppet/pull/4324). The solutions are to either:

- get a GitHub admin to merge the PR
- reopen the PR as a branch within this repo.

**Comment by alexmuller** [comment]
Yeah, we don't allow forks to run tests on our Jenkins because that would allow anyone to execute arbitrary code in our CI environment (my internet isn't good enough to merge this or I would).

**Comment by jackscotti** [comment]
@alexmuller happy if I merge?

**Comment by alexmuller** [comment]
By all means! If the tests pass (on Travis in this case) and a 2nd person has looked at it it's ok to merge.

**Comment by jackscotti** [comment]
Just realised I can't press the button. 😔

**Pull request merged**
