### PR TITLE
Update Filebeat to use only Logit on SSL

### PR DESCRIPTION
**Pull request by afda16**
Update govuk_beat configuration to use SSL and install the Logit
intermediate certificate.

### CODE REVIEW

**Comment by SamLR** [comment]
Is this going to break exporting things to the K8 ELK stack?

**Comment by afda16** [comment]
It's going to disable the K8s stack

**Comment by SamLR** [comment]
Fair enough, just wanted to be sure. I'm happy with it.

**Comment by surminus** [comment]
:+1:

**Comment by afda16** [comment]
I updated the request, it doesn't look like it needs the intermediate certificate

**Comment by surminus** [comment]
Merge when ready

**Pull request merged**
