### PR TITLE
Bug fixes for Terraform and Lambda deployments

### PR DESCRIPTION
**Pull request by alexmuller**

### CODE REVIEW

**Comment by surminus** [comment]
:+1: That's weird, I thought I'd had set it up to explictly set `TF_VAR_LAMBDA_FILENAME` so it correctly triggered the Terraform build, but I guess I never committed it. Merge away.

**Comment by alexmuller** [comment]
Oh yeah, does the deploy Lambda app job need to set `TF_VAR_LAMBDA_FILENAME` when it calls the downstream job?

**Comment by surminus** [comment]
Yes as there is a conditional in the Rakefile, but it should automagically be set by the `jenkins.sh` task in the _other_ repo.

**Comment by alexmuller** [comment]
Sorry, I'm getting confused. Is it [this thing](https://github.com/alphagov/govuk-lambda-app-deployment/blob/0fea2136e16080faf04e6910203550d77e067fff/email_alert_notifications/jenkins.sh) that should be setting `TF_VAR_LAMBDA_FILENAME`?

**Comment by alexmuller** [comment]
Pushed some more commits. We also need https://github.com/alphagov/packager/pull/113.

**Comment by surminus** [comment]
:+1: Probably a more sane way to do it.

**Pull request merged**
