### PR TITLE
Remove VMware Fusion support in development

### PR DESCRIPTION
**Pull request by alexmuller**
I'm not sure whether anybody uses this anymore. If you do, please leave a comment.

### CODE REVIEW

**Comment by mattbostock** [comment]
:+1:

**Comment by surminus** [comment]
:+1: I guess you're leaving a bit of time just incase somebody comments?

**Comment by deanwilson** [comment]
Simplification is good. Merge away.

**Comment by alexmuller** [comment]
Rebased against master to fix a merge conflict.

**Comment by mattbostock** [comment]
Merge when green.

**Pull request merged**
