### PR TITLE
Add API users to CI

### PR DESCRIPTION
**Pull request by djsd123**
The user accounts that make api calls to jenkins from running jobs.

### CODE REVIEW

**Comment by alexmuller** [comment]
I think before we add user accounts it would be useful to understand what they're doing and add it to the commit message briefly so we have a reference:

- agent: absolutely no idea, should this exist? I can't think why the username would need to be configurable. The commit message here implies it's to do with connecting to the master but I don't know if that's necessary? https://github.com/alphagov/ci-puppet/commit/343395d352bed84b770955add5680e65924df453
- pingdom: monitoring maybe? Not sure, I don't think we need this one: https://github.com/alphagov/ci-puppet/commit/89cd52c7092ad5728c1c9f324675f09ad3f46faf
- github_build_trigger: used by the Heroku GitHub trigger to make builds happen
- deploy_jenkins: used by [some deploy jobs](https://github.com/alphagov/govuk-app-deployment/blob/fe36155a42e51da5b0b0067076985317bba67ec9/router/config/deploy.rb#L22) to download artefacts

This class also probably needs to be included somewhere.

**Comment by surminus** [comment]
RE: class inclusion, because we have to keep continuing to rebase commits against changes I'm going to split out https://github.com/alphagov/govuk-puppet/pull/5052 to make it much simpler so we can merge it and then put additions to the master on top of that.

**Comment by djsd123** [comment]
@alexmuller 
Fair point.  I would describe it like: Accounts used to authenticate against the Jenkins API by other services.

Putting more detail at this point might distract from the fact that this is a port of functionality from one repo to another.  At this point, determining whether these accounts are required would be a guess at best. At least until we have the Jenkins instances up and running with jobs loaded.

It's possible the agent account is still valid and poorly named.  Probably used by some webhook or something.  We won't know until we have the service up and running.

**Comment by djsd123** [comment]
I'll add the master class to the node class in another PR

**Comment by djsd123** [comment]
We're going to forward fix this.  We'll add accounts as we need them.

**Pull request closed without merging**
