### PR TITLE
Remove fail2ban.

### PR DESCRIPTION
**Pull request by deanwilson**
After a discussion we no longer want to run Fail2Ban.

https://trello.com/c/7lnrxg1a

### CODE REVIEW

**Comment by surminus** [comment]
:eggplant:

**Comment by deanwilson** [comment]
Force pushed new commit with more details/context from the requesting ticket.

**Comment by mattbostock** [comment]
The cached module needs to be removed.

**Comment by mattbostock** [comment]
:+1: Merge when ready.

**Pull request merged**
