### PR TITLE
Remove references and class for old Mapit

### PR DESCRIPTION
**Pull request by klssmith**
- Removed all references for old Mapit servers

Mobbed by @brenetic @emmabeynon @klssmith

### CODE REVIEW

**Comment by alexmuller** [comment]
This pull request is great! Things that delete huge parts of our Puppet repo are the best :tada: 

The tests are failing because [the backend loadbalancer](https://github.com/alphagov/govuk-puppet/blob/e23d71a92c132ad38b4236f2ab066d05036114db/modules/govuk/manifests/node/s_backend_lb.pp) has a variable for `mapit_servers` which can go. The node manifest for [the old mapit_server machines](https://github.com/alphagov/govuk-puppet/blob/e23d71a92c132ad38b4236f2ab066d05036114db/modules/govuk/manifests/node/s_mapit_server.pp) can also disappear. Finally there's a bit more hieradata which can be removed, a `class` file for `mapit_server` and a line in the `vagrant` credentials file.

There will also be some stuff to tidy up in the deployment and govuk-provisioning repos.

**Comment by klssmith** [comment]
@alexmuller All changes should now be made and the tests are now passing - thanks

**Comment by alexmuller** [comment]
Sorry to nitpick, there's one more bit of hieradata in `vagrant_credentials` for `mapit::config::django_secret_key`. Apart from that this is perfect!

**Comment by klssmith** [comment]
@alexmuller 👍  Thanks, have removed it and rebased

**Comment by alexmuller** [comment]
Sorry, I keep finding new things I'd forgotten existed. There's also a file at `hieradata/class/mapit_server.yaml` which applies to the `mapit_server` machines you're removing.

**Comment by klssmith** [comment]
@alexmuller Should we also remove references to mapit_server from `manifests/node/s_api_lb.pp`?

**Comment by alexmuller** [comment]
I think those ones are ok because that's an array which is set from hieradata which references the new mapit machines from the API loadbalancer (the old ones were on the backend loadbalancer).

This all looks good to me! Merge whenever you want :+1:

**Pull request merged**
