### PR TITLE
Onboarding, Added oliverroberts to Integration.yml and created oliverroberts.pp file

### PR DESCRIPTION
**Pull request by ollyroberts**
Added oliverroberts to the users::username values

### CODE REVIEW

**Review by maxf — APPROVED** [review]
LGTM. Please change the commit messages to include your name, for extra visibility

**Comment by benjamineskola** [comment]
Hi both: could you also add yourself to alphagov/govuk-user-reviewer? Thanks.

**Comment by benjamineskola** [comment]
@maxf There's no `ssh_username` key specified, which means the user reviewer raises an error that SSH access has been granted.

(Apologies, copied and pasted the wrong username earlier but the correct error message.)

**Comment by maxf** [comment]
yes sorry, the email didn't show the text below the first line. We're on it.

**Pull request merged**
