### PR TITLE
Add ruby 2.3.1

### PR DESCRIPTION
**Pull request by h-lame**
Fix the Gemfile.lock and add ruby 2.3.1 (slightly more info in each commit).

### CODE REVIEW

**Comment by andrewgarner** [comment]
This will also need a Ruby 2.3.1 package being created and added to our repository. @gpeng can probably explain better than I can.

**Comment by h-lame** [comment]
Oh :( I hoped that rbenv would "just know", thanks for the heads up.

**Comment by andrewgarner** [comment]
https://github.gds/pages/gds/opsmanual/infrastructure/howto/adding-a-ruby-version.html

**Comment by h-lame** [comment]
Adding DNM tag while I build the ppa.

**Comment by alexmuller** [comment]
The opsmanual instructions are for debuild but you may find it more simple to build it with fpm. Either will work.

**Comment by alexmuller** [comment]
Also see #4651 :)

**Comment by alexmuller** [comment]
I think this is ready to go out now:

```
fab $environment puppet_class:govuk::node::s_app_server do:'apt-cache policy rbenv-ruby-2.3.1'
```

You could use a newer version of Bundler if you wanted to but either way :+1:

**Comment by elliotcm** [comment]
@h-lame @alexmuller This is causing problems in production for our EFG servers which seem to not have the package `rbenv-ruby-2.3.1` available to them.

**Pull request merged**
