### PR TITLE
updates duplicity module to latest

### PR DESCRIPTION
**Pull request by jonauman**

### CODE REVIEW

**Comment by jonauman** [comment]
There was a trailing space in the sha hash for the duplicity module. I fixed it but still ran into this issue:

```
DaveOps:govuk-puppet jonauman$ bundle exec rake --trace librarian:install
** Invoke librarian:install (first_time)
** Execute librarian:install
Could not find a local copy of git://github.com/alphagov/puppet-duplicity.git at 99d165aa2a7949e7dee15184cfd4570fe72e965c.
rake aborted!
```

I had to manually update the module after that:

```
DaveOps:govuk-puppet jonauman$ rake librarian:update[alphagov/duplicity]
gzip: /Users/jonauman/DevOps/GDS/govuk-puppet/vendor/puppet/source/99d165aa2a7949e7dee15184cfd4570fe72e965c.tar.gz already exists -- skipping
```

After that, librarian-install started working again:
DaveOps:govuk-puppet jonauman$ bundle exec rake librarian:install
DaveOps:govuk-puppet jonauman$

**Comment by jonauman** [comment]
rake librarian:install              # Install modules from local cache
rake librarian:package              # Install modules and update cache
rake librarian:update[module_name]  # Update a module version and cache

I think we want to use librarian:package, since the local cache can get foo barred

**Comment by alexmuller** [comment]
The tests are failing here because the updated module hasn't been cached in the `vendor/` directory.

**Comment by alexmuller** [comment]
I ran these commands following the README:

```
bundle exec rake 'librarian:update[alphagov/duplicity]'
git add vendor/puppet/source/99d165aa2a7949e7dee15184cfd4570fe72e965c.tar.gz
git rm vendor/puppet/source/e238b6708c6d0a379d06599b25e6d2b68c3b8852.tar.gz
```

**Comment by deanwilson** [comment]
Merge away.

**Comment by deanwilson** [comment]
Might also be worth adding a comment as to why we upgraded this module.

**Pull request merged**
