### PR TITLE
Add `service_template` param to passive checks

### PR DESCRIPTION
**Pull request by alexmuller**
We want to make some passive checks more important than just regular service.

### CODE REVIEW

**Comment by deanwilson** [comment]
The code looks fine. Merge when green.

**Comment by rjw1** [comment]
`service_template` may be a better variable name than `use` but thats bikeshedding. 
Good to merge otherwise

**Comment by deanwilson** [comment]
Actually I think @rjw1 has a good point. Changing the name will make life easier when we return to this code.

**Comment by alexmuller** [comment]
Sure, updated!

**Comment by deanwilson** [comment]
Looks much nicer. Thank you.

**Pull request merged**
