### PR TITLE
Fix YAML syntax

### PR DESCRIPTION
**Pull request by gpeng**
A formatting error in this job was causing it to fail.

### CODE REVIEW

**Comment by tijmenb** [comment]
👍 sorry about that.

This is the second YAML error this week (https://github.com/alphagov/govuk-puppet/pull/4592). @alexmuller do you know if it's possible to test these files in CI?

**Comment by alexmuller** [comment]
I think this is covered by the functional testing @deanwilson has been thinking about recently.

This isn't a problem with compiling the catalog (which works fine and is something we test), it's a problem with applying jenkins-job-builder given our broken YAML.

**Comment by gpeng** [comment]
Could we add a linter for it? https://github.com/adrienverge/yamllint type of thing?

**Comment by alexmuller** [comment]
We could, but we need to render the ERB as YAML before linting (using the Puppet catalog compilation) which I think is where that gets tricky.

**Comment by gpeng** [comment]
True although in both the recent cases the `erb` files linted as YAML would have failed when they had the issues in them and passed when they were fixed. Expanding the erb could still introduce invalid YAML but it would have helped still in these cases.

**Pull request merged**
