### PR TITLE
Mirror repository for elasticsearch 5 releases

### PR DESCRIPTION
**Pull request by MatMoore**
We're aiming to upgrade to this version before 2.4 reaches its end of life
early next year.

See https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html#deb-repo

### CODE REVIEW

**Comment by surminus** [comment]
Can we remove anything related to 1.x while you're there?

**Comment by MatMoore** [comment]
@surminus I had a look and there's some left over stuff related to api-elasticsearch, which I'm assuming we can delete now.

As far as I can tell the AWS and training environments are still set to use 1.7, so I'm not sure if its safe to delete those repos yet.

**Comment by surminus** [comment]
Ah OK, no worries, I will check next week. :+1:

**Comment by MatMoore** [comment]
Just pushed one more change to deploy the migration plugin. This'll let us enable some deprecation logging on integration.

**Pull request merged**
