### PR TITLE
Added user gregorambrozic

### PR DESCRIPTION
**Pull request by ambrozic**

### CODE REVIEW

**Comment by rubenarakelyan** [comment]
Couple of things to get the tests passing:

1. Your username should be `gregorambrozic` (first name and last name)
2. Your SSH key needs to be at least 4096 bits

**Comment by ambrozic** [comment]
@rubenarakelyan thanks for review. pull request updated.

**Comment by rubenarakelyan** [comment]
You'll also need to rename the `.pp` file name to match your username :)

**Comment by ambrozic** [comment]
ah. fixed.

**Comment by boffbowsh** [comment]
Hi @ambrozic! 👋

**Comment by boffbowsh** [comment]
Can you submit this from alphagov instead of a fork? Ask your Tech Lead to give you access

**Comment by ambrozic** [comment]
Hey @boffbowsh :)

I will submit from upstream as soon as i get access. Its already in process and it should happen soon.

**Comment by boffbowsh** [comment]
I've added you now Gregor

**Comment by ambrozic** [comment]
thanks @boffbowsh , ill create new PR from upstream.

**Pull request closed without merging**
