### PR TITLE
Add Jack Scotti's 2nd SSH key

### PR DESCRIPTION
**Pull request by jackscotti**

### CODE REVIEW

**Comment by tijmenb** [comment]
You'll need to update your git config in vagrant to get the commit properly attributed to your account (it's vagrant@development.development now).

**Comment by jackscotti** [comment]
@tijmenb updated

**Comment by tijmenb** [comment]
@jackscotti do you still need this? Seems to be unusual.

**Comment by jackscotti** [comment]
I am okay with getting this not merged but would like someone to expand a bit more on the reason why we are not happy with adding new ssh keys.

**Comment by jackscotti** [comment]
Had a chat with @alexmuller in real life. Closing this for now.

**Pull request closed without merging**
