### PR TITLE
add tdrv user

### PR DESCRIPTION
**Pull request by TDRV**

### CODE REVIEW

**Comment by boffbowsh** [comment]
Only members of GOV.UK staff can add themselves to our infrastructure.

**Comment by TDRV** [comment]
Am I added to Gov.UK team?
_Ask your tech lead to add you to the alphagov organisation. You will have to be added to the GOV.UK team to get access to repos & CI._

**Comment by boffbowsh** [comment]
Which team are you on?

**Comment by TDRV** [comment]
actually I don't know which team should I join.

I hold the position of the IT Sector Lead
in Administrative Services Reform Office 
at the Ministry of economy of Ukraine.
 
Within the scope of reforms in administrative services, we are working on the administrative services portal.
 
I'm trying to deploy Gov.uk on our servers according to instruction.
https://docs.publishing.service.gov.uk/manual/get-started.html#header

**Comment by boffbowsh** [comment]
Those instructions are for working directly on GOV.UK services as a member of GOV.UK staff. I can't give you access to our infrastructure. You don't need access to this Github organisation to run GOV.UK services on your own infrastructure.

**Comment by TDRV** [comment]
Thanks for clarification.
Can you give me the instruction for deploying GOV.UK on own infrastructure?
Another words, how can I try to use Gov.UK? May be you have demo instance?

**Pull request closed without merging**
