### PR TITLE
Remove Alex Muller

### PR DESCRIPTION
**Pull request by brenetic**
[Trello card](https://trello.com/c/1QxAqimW/297-leaver-alex-muller-16-june)

### CODE REVIEW

**Comment by surminus** [comment]
😭

**Comment by alexmuller** [comment]
👋

**Comment by rjw1** [comment]
🎉 🎈

**Comment by surminus** [comment]
Sniffles

**Comment by joshmyers** [comment]
noooooo

:(:(:(:(:(:(:(:(:(

**Comment by dcarley** [comment]
tenor

**Comment by philandstuff** [comment]
Sad Taylor Swift

**Comment by bazbremner** [comment]
👋

**Comment by ajlanghorn** [comment]
giphy

**Comment by davidillsley** [comment]
👋

**Comment by alexmuller** [comment]
So proud of your gif game 😊 

I'm only really qualified to comment on the Taylor ones. You've got such a great variety. Here are the sources in case you were wondering (don't lie, I know you were):

- [Smashing up the car in _Blank Space_](https://www.youtube.com/watch?v=e-ORhEE9VVg#t=3m23s)
- [An interview with Vcast when _Fearless_ was released](https://www.youtube.com/watch?v=fv9V-q903Nw#t=1m23s) (the actual quote is great 😉)
- [The snow scene from _Bad Blood_](https://www.youtube.com/watch?v=QcIy9NiNbmo#t=2m8s)
- [_Mine_ being performed on the Speak Now World Tour](https://www.youtube.com/watch?v=mMz7eSPgznc#t=2m30s)

See you round!

**Pull request merged**
