### PR TITLE
Add new user Tom Hipkin

### PR DESCRIPTION
**Pull request by benilovj**
Reopening https://github.com/alphagov/govuk-puppet/pull/4324 as a branch inside this repository to make Jenkins happy.

### CODE REVIEW

**Comment by christophwong** [comment]
Code looks good to me. Assuming the ssh-key is correct.
Is there a reason to not use gov.uk email?

**Comment by christophwong** [comment]
is it ok to not use digital.cabitnet-office.gov.uk email domain?

**Comment by benilovj** [comment]
I've updated the PR with Tom's `digital.cabinet-office.gov.uk` email.

**Comment by christophwong** [comment]
👍 mergeable

**Pull request merged**
