### PR TITLE
Revert "Reboot MongoDB machines overnight"

### PR DESCRIPTION
**Pull request by mattbostock**
Reverts alphagov/govuk-puppet#3877

On further investigation, `rs.status().ok()` returns a value of `1` even if there is no primary node.

I'd like to revert this until we have a clearer picture of what a healthy status looks like given the current read preferences of our applications using Mongo.

Example:

```json
production:SECONDARY> rs.status()
{
    "set" : "production",
    "date" : ISODate("2016-01-13T11:27:40Z"),
    "myState" : 2,
    "syncingTo" : "api-mongo-2:27017",
    "members" : [
        {
            "_id" : 0,
            "name" : "api-mongo-1:27017",
            "health" : 1,
            "state" : 2,
            "stateStr" : "SECONDARY",
            "uptime" : 23960,
            "optime" : Timestamp(1452684160, 2),
            "optimeDate" : ISODate("2016-01-13T11:22:40Z"),
            "errmsg" : "syncing to: api-mongo-2:27017",
            "self" : true
        },
        {
            "_id" : 1,
            "name" : "api-mongo-2:27017",
            "health" : 1,
            "state" : 2,
            "stateStr" : "SECONDARY",
            "uptime" : 23958,
            "optime" : Timestamp(1452684160, 2),
            "optimeDate" : ISODate("2016-01-13T11:22:40Z"),
            "lastHeartbeat" : ISODate("2016-01-13T11:27:38Z"),
            "lastHeartbeatRecv" : ISODate("2016-01-13T11:27:39Z"),
            "pingMs" : 0,
            "syncingTo" : "api-mongo-1:27017"
        },
        {
            "_id" : 2,
            "name" : "api-mongo-3:27017",
            "health" : 0,
            "state" : 8,
            "stateStr" : "(not reachable/healthy)",
            "uptime" : 0,
            "optime" : Timestamp(1452684160, 2),
            "optimeDate" : ISODate("2016-01-13T11:22:40Z"),
            "lastHeartbeat" : ISODate("2016-01-13T11:27:38Z"),
            "lastHeartbeatRecv" : ISODate("2016-01-13T11:25:49Z"),
            "pingMs" : 0
        },
        {
            "_id" : 3,
            "name" : "api-mongo-4:27017",
            "health" : 0,
            "state" : 8,
            "stateStr" : "(not reachable/healthy)",
            "uptime" : 0,
            "optime" : Timestamp(1452684160, 2),
            "optimeDate" : ISODate("2016-01-13T11:22:40Z"),
            "lastHeartbeat" : ISODate("2016-01-13T11:27:38Z"),
            "lastHeartbeatRecv" : ISODate("2016-01-13T11:27:06Z"),
            "pingMs" : 0,
            "syncingTo" : "api-mongo-2:27017"
        }
     ],
    "ok" : 1
}
```

### CODE REVIEW

**Comment by alexmuller** [comment]
Interesting, I apparently entirely failed to implement this method: https://github.com/alphagov/fabric-scripts/blob/c8e7c36a97b3d90a9bebedf40628ed1886ff589c/mongo.py#L126-L134

I'm not sure what I was thinking at the time, sorry.

**Comment by tombooth** [comment]
I'd like to add that at the moment this seems to be breaking the dev vm as `govuk_unattended_reboot::mongodb` is included on all machines but `govuk_unattended_reboot` isn't included on the dev vm. This causes the former to fail as it is lacking the configuration directory setup by the later.

Turns out `s_base` is not the base of `s_development`, how confusing.

**Comment by mattbostock** [comment]
thisisfine

**Comment by mattbostock** [comment]
@alexmuller Don't worry, checking `rs.status().ok` seems like an entirely reasonable thing to do.

**Comment by alexmuller** [comment]
> Turns out `s_base` is not the base of `s_development`, how confusing.

I had a quick look a week or two ago at exactly this because it also confused me, but it turns out they're quite different machines. It'd be really nice if we could make this the case.

**Comment by mattbostock** [comment]
@alexmuller Are you happy to merge this? I'm worried about Puppet being deployed with this change.

**Pull request merged**
