### PR TITLE
Goodbye Jack Scotti

### PR DESCRIPTION
**Pull request by kevindew**
👋😢

### CODE REVIEW

**Comment by djsd123** [comment]
I thought the correct way to remove a user was to `ensure => absent`.

**Comment by cbaines** [comment]
> I thought the correct way to remove a user was to ensure => absent.

Hmm, I can see how that might be necessary.

In this case as its just integration, I'd expect the effect to be the same, but maybe its worth for consistency always removing with `ensure => absent`?

**Comment by kevindew** [comment]
@djsd123 sure is there an example of that?

**Comment by cbaines** [comment]
> @djsd123 sure is there an example of that?

This is the most recent change: 7889704d10ad4bd25b425840159e4c6227ca5cf5

**Comment by kevindew** [comment]
@cbaines Thanks, I'll get this updated.

**Comment by kevindew** [comment]
Ok - I've updated this now 👍

**Comment by cbaines** [comment]
I'm not sure, but I would guess that you need to keep `jackscotti` in hieradata for the `absent` thing to have an effect?

**Comment by djsd123** [comment]
Sweet. I think the way you did first partially removes a user and leaves behind ssh config/stuff.  No harm......
FYI; declaring the resource name is all you need but makes no difference dude.  merge away 👍 
```
govuk_user { 'jackscotti':
  ensure   => absent,
}
```

**Comment by djsd123** [comment]
Hi @kevindew,

@cbaines is correct.  To purge a user, you'll need to keep their name in hiera.  I'd just do it the way you were going to in the first place. Everything is unjustly coupled in this repo. Sorry to stick my oar in.

**Comment by kevindew** [comment]
@djsd123 No problem - Does seem better to remove the files but a tad painful. I've reset this to how it was now.

**Pull request merged**
