### PR TITLE
Add chrislowis user

### PR DESCRIPTION
**Pull request by chrislo**
I am working at GDS through Go Free Range Ltd. Contact:
chris.lowis@digital.cabinet-office.gov.uk.

### CODE REVIEW

**Comment by boffbowsh** [comment]
This is failing CI, your key must be 4096bits or stronger. Use `ssh-keygen -b 4096` to generate a new key.

**Comment by chrislo** [comment]
Thanks @boffbowsh - I've increased my key length in 2897e3.

**Comment by boffbowsh** [comment]
You're missing a trailing comma on your ssh key line

**Comment by chrislo** [comment]
Apologies @boffbowsh - I was just working through the travis output trying to work out what had happened. Thanks!

**Comment by boffbowsh** [comment]
The comma needs to be on line 6, not 7. It's so that we can add new lines to config like that without adding diff noise.

**Comment by boffbowsh** [comment]
If this passes would you be able to squash these into one commit please? Thanks :)

**Comment by chrislo** [comment]
Ugh, sorry @boffbowsh - let me know when I finally get it right and I'll squash the noise out of the history.

**Comment by chrislo** [comment]
I rebased onto master, squashed the noise and force pushed.

**Pull request merged**
