### PR TITLE
Add authenticated Docker registry for AWS Integration

### PR DESCRIPTION
**Pull request by fredericfran-gds**
We enable authenticated puppet docker registry for the AWS Integration
environment. This is to mitigated against the new Docker limits on
docker pulls for anonymous/unpaid accounts.

2nd commit fixes Docker module. 

Tested by:
1. creating a private repo on docker hub and trying with puppet having installed this PR.

Future work:
If all goes well, install in other environments.

Ref:
1. [Trello Card](https://trello.com/c/M3zyF5kM/3898-identify-govuk-components-and-jenkins-jobs-which-pull-images-from-docker-hub-investigate-an-option-to-enable-authentication-for)
2. [secrets pr](https://github.com/alphagov/govuk-secrets/pull/1081)

### CODE REVIEW

**Review by smford — APPROVED** [review]
LGTM, done as a pair

**Review by smford — APPROVED** [review]
excellent work

**Review by bilbof — APPROVED** [review]
LGTM, it looks like we're just using this (https://forge.puppet.com/puppetlabs/docker), is that being configured in the govuk-secrets repo?

**Comment by fredericfran-gds** [comment]
yes.

**Pull request merged**
