### PR TITLE
Add DR machines to shutdown overnight

### PR DESCRIPTION
**Pull request by surminus**
We'll save some more money!

Requires https://github.gds/gds/deployment/pull/967

### CODE REVIEW

**Comment by boffbowsh** [comment]
I thought the idea behind the DR machines is that they're warmed and ready to go as data sources for our infrastructure should we lose our primary DC? If we shut them off overnight and we lost the primary DC while the DR machines are off, we'll need to restore them from backup first before they're usable. Plus we'll need to actually turn them on manually as we'll have lost the production Jenkins.

In addition, when they get turned on in the morning they may not be able to catch up with replication - they might be too far behind.

If this has all been considered and discussed, I'll shut up :)

**Comment by surminus** [comment]
@boffbowsh it's just for Integration. I probably should have been clearer! They just need to be turned off like we do for the rest of the machines in Integration.

**Comment by boffbowsh** [comment]
That makes more sense :)

**Comment by deanwilson** [comment]
Code looks good. Merge away.

**Pull request merged**
