### PR TITLE
[DO NOT MERGE] Install Ruby 2.3.1

### PR DESCRIPTION
**Pull request by gpeng**
This adds the latest available stable ruby.

### CODE REVIEW

**Comment by alexmuller** [comment]
I think it will need adding to here first: https://launchpad.net/~gds/+archive/ubuntu/govuk

Docs: https://github.gds/pages/gds/opsmanual/infrastructure/howto/adding-a-ruby-version.html

**Comment by gpeng** [comment]
Oh... I thought that seemed overly straight forward. I'll have a go 😄

**Comment by gpeng** [comment]
We've opened https://github.com/alphagov/govuk-puppet/pull/4651 to try and add support for `lsbcodename` to allow us to easily build separate packages for different Ubuntu releases from `fpm`

**Comment by deanwilson** [comment]
Upstream has merged https://github.com/bernd/fpm-cookery/pull/158

**Comment by deanwilson** [comment]
Can you link to the packager PR here when it's ready please?

**Comment by h-lame** [comment]
Closing in favour of #4755

**Pull request closed without merging**
