### PR TITLE
Add script for running app consoles.

### PR DESCRIPTION
**Pull request by elliotcm**
Supports Rails apps and apps with a `console`
binary in the root (such as rummager).

### CODE REVIEW

**Comment by boffbowsh** [comment]
😍 merge when green 👍

**Comment by tijmenb** [comment]
❤️

**Comment by tuzz** [comment]
💋

**Comment by alexmuller** [comment]
I'm not sure this will actually end up on the box, it might need to be included in the `govuk_scripts` class.

**Comment by elliotcm** [comment]
@alexmuller spoil sport: https://github.com/alphagov/govuk-puppet/pull/4352

**Pull request merged**
