### PR TITLE
Update puppetlabs_spec_helper to 1.0.1

### PR DESCRIPTION
**Pull request by deanwilson**

### CODE REVIEW

**Comment by mattbostock** [comment]
@deanwilson Can you please say why you're upgrading it in your commit message?

**Comment by deanwilson** [comment]
No single reason. Upgrading because we're very behind and bug fixes are good.

**Comment by mattbostock** [comment]
Thanks @deanwilson - even if there's no specific reason, it's useful to say why in the commit message so that others aren't left wondering if something breaks or behaviour changes.

**Comment by deanwilson** [comment]
Does mean I'm clear to merge?

**Comment by mattbostock** [comment]
Sorry - I should have been clearer. I was suggesting that you say in the commit message that you're upgrading just to keep up-to-date.

**Comment by mattbostock** [comment]
Superseded by #4012. Thanks @deanwilson

**Pull request closed without merging**
