### PR TITLE
Add manifest + user info for Tim Blair

### PR DESCRIPTION
**Pull request by timblair**
Also tidy up an out-of-alpha-order name that was making me twitch.

### CODE REVIEW

**Comment by boffbowsh** [comment]
You stole my class

**Comment by timblair** [comment]
@boffbowsh: You're right.  I did.  What a great start...  `<facepalm>`

**Comment by alexmuller** [comment]
Looks right to me, welcome! :+1:

**Comment by boffbowsh** [comment]
I'm fairly sure I did the exact same thing with Dom's user class when I joined...

**Pull request merged**
