### PR TITLE
Jenkins job to publish dept. projects content

### PR DESCRIPTION
**Pull request by ssatish**

### CODE REVIEW

**Comment by bradwright** [comment]
This appears to be based off #3990. Are you planning on closing that?

Also the PR description needs work as this change is now bigger than just the giturl change.

**Comment by ssatish** [comment]
@bradwright. I plan to close #3990. Thats why I pinged you to figure out what your preference would be. This PR incorporates both changes. 
Let me know what you want me to do.

**Comment by bradwright** [comment]
@ssatish let's do this one as it's actually right, but squash the commits (they should be one change, to add the job).

**Comment by ssatish** [comment]
@bradwright They are two different commits semantically.

**Comment by ssatish** [comment]
First one hanldes publishing existing content. And second one is fixing a url bug for two different tasks.
I can still squash commits if you prefer

**Comment by bradwright** [comment]
In that case you should change the other commit to describe the change, eg `Fix Git remote for existing content job`

**Comment by ssatish** [comment]
@bradwright done.

**Comment by bradwright** [comment]
Thanks! :+1:

**Pull request merged**
