### PR TITLE
Remove Ben Hyland account

### PR DESCRIPTION
**Pull request by djsd123**
De-provisioning Ben's account as he has moved to Gaap.

### CODE REVIEW

**Comment by deanwilson** [comment]
Can we add a `FIXME:` to remove the absent user once the deletes have gone through please. Other than that Merge away.

**Comment by alexmuller** [comment]
Users are purged so we can just delete the file without ensuring it's absent: https://github.com/alphagov/govuk-puppet/blob/0db6b25636c74f970852000efd6d0f31bd3ebdaa/modules/users/manifests/init.pp#L38

**Comment by deanwilson** [comment]
This will leave the SSH key in the home directory.

**Comment by alexmuller** [comment]
:+1:

**Comment by djsd123** [comment]
@deanwilson , @alexmuller , Think I should heed Aaron's words that we should have a leaver's ticket from "Finding Things".

**Pull request merged**
