### PR TITLE
Enable continuous deployment for contacts-admin

### PR DESCRIPTION
**Pull request by benjamineskola**
https://trello.com/c/hwPMNAnb/340-enable-continuous-deployment-for-contacts-admin

### CODE REVIEW

**Review by kevindew — DISMISSED** [review]

**Comment by kevindew** [comment]
Actually just a thought. Is this app called contacts-admin in this context?

**Comment by benjamineskola** [comment]
> Is this app called contacts-admin in this context?

Good point, I saw it referred to as `contacts` somewhere; I'll double-check.

**Comment by kevindew** [comment]
You’ll have to add the health check url in manually as that’s on contacts-admin domain - it’s such a pain when you have an unconventional repo.

Probably worth doing a test deploy to integration too to check it all integrates

**Review by kevindew — APPROVED** [review]

**Comment by benjamineskola** [comment]
This has applied nicely to integration and the URL is successfully readable from Jenkins, so I'm going to go ahead and merge this and the associated PRs now.

**Pull request merged**
