### PR TITLE
[WIP] Add cadvisor running code

### PR DESCRIPTION
**Pull request by deanwilson**
As we add more docker containers to our stack we need ways to monitor
and observe their running. Cadvisor provides a quick to deploy,
low resource overhead initial pass at this.

### CODE REVIEW

**Comment by th31nitiate** [comment]
@deanwilson Is this really what we are looking to for monitoring our containers ?

I believe prometheus will be a more suitable robust solution for this.

**Comment by deanwilson** [comment]
cAdvisor is one of the datasources prometheus will need to scrape. In the meantime, as we don't actually have prometheus, it will provide visibility somewhere we have none and require no rework once prometheus is available to us.

**Comment by th31nitiate** [comment]
Ok, I have reviewed the following: https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md

This means sounds interesting and should be workable solutions. I have just never been a big fan of it based on the way it stores its data in Kubernetes. I think for ad-hoc solutions is cool where we deploy as daemon on node running docker.

I am not sure how or where we may deploy the export when moving to Kubernetes. 

How are we going to centralise these metrics, are they going to graphite ?

**Comment by deanwilson** [comment]
I'm closing this as it's not part of this quarters work.

**Pull request closed without merging**
