### PR TITLE
Add my public key to puppet

### PR DESCRIPTION
**Pull request by adrianclay**
So I can log into the E2E Jenkins boxes

### CODE REVIEW

**Comment by kevindew** [comment]
Looks good but you'll need to also be in hieradata/integration as CI is not on AWS

**Comment by adrianclay** [comment]
Thanks for that!

I feel misled by the manual now https://docs.publishing.service.gov.uk/manual/get-started.html#3-create-a-user-in-integration-and-ci

**Comment by kevindew** [comment]
D'oh I'll get a quick PR up to fix that.

**Comment by kevindew** [comment]
https://github.com/alphagov/govuk-developer-docs/pull/715

**Pull request merged**
