### PR TITLE
Add a Grafana dashboard for NGinx logs

### PR DESCRIPTION
**Pull request by cbaines**
On both production and staging if you would like to test.

nginx_logs

### CODE REVIEW

**Comment by alexmuller** [comment]
I think the list of machines in this JSON file will get out of date quite quickly as people forget to add and remove them. What about templating this file and creating the list of machines dynamically using the output of `govuk_node_list` and maybe the Puppet `generate()` function?

**Comment by cbaines** [comment]
> I think the list of machines in this JSON file will get out of date quite quickly as people forget to add and remove them. What about templating this file and creating the list of machines dynamically using the output of govuk_node_list and maybe the Puppet generate() function?

Shouldn't be necessary to template it, as Grafana will regenerate the list from the data in Graphite when the dashboard is opened in the users browser. I'd prefer to just remove all the entries if you don't want them in the repository?

**Comment by alexmuller** [comment]
If they're generated by Grafana then not having them in this repo would be great, thanks! The same for domains and status codes if those are also generated.

**Comment by cbaines** [comment]
> If they're generated by Grafana then not having them in this repo would be great, thanks! The same for domains and status codes if those are also generated.

Ok, now updated.

**Pull request merged**
