### PR TITLE
Govuk Release app Postgresql backend

### PR DESCRIPTION
**Pull request by djsd123**
What
Govuk is moving away from MySql in favour of Postgres. This relates to https://github.com/alphagov/release/pull/110

How
Using the govuk_postgresql defined type, I have added the config parameters for the
release app's database configuration file.

### CODE REVIEW

**Comment by djsd123** [comment]
Note:
Class params; postgresql_release and backend_ip_range need to be defined.

**Comment by alexmuller** [comment]
I wonder if we should keep the MySQL database defined in Puppet until we're ready to destroy it (after the data has been migrated and we're running PostgreSQL in production).

**Comment by boffbowsh** [comment]
We should definitely do that thing that Alex said

**Comment by deanwilson** [comment]
Other than the horribly named `$mysql_release` this looks ok to my naive eyes. @alexmuller / @surminus mergeable?

Do we need two separate passwords or should we keep them insync between the two DB engines and have a release_db_password value instead of different ones for mysql and postgres?

**Comment by surminus** [comment]
I think this looks mergeable. Having just one password might be tidier, but I'm not fussed either way.

**Comment by alexmuller** [comment]
Going to close this for the time being because things have changed in the time since this was done.

**Pull request closed without merging**
