### PR TITLE
Upgrade gor to 0.14.1

### PR DESCRIPTION
**Pull request by alexmuller**
Depends on:

- [x] https://github.com/alphagov/govuk-puppet/pull/4617
- [x] https://github.com/alphagov/packager/pull/115

### CODE REVIEW

**Comment by deanwilson** [comment]
Code looks fine. Merge when ready.

**Comment by alexmuller** [comment]
Had to update to change the `apt::source`, sorry.

**Comment by deanwilson** [comment]
Merge it.

**Comment by deanwilson** [comment]
Merge away.

**Pull request merged**
