### PR TITLE
Remove panopticon

### PR DESCRIPTION
**Pull request by tijmenb**
This removes the panopticon application.
 
https://trello.com/c/dGPNmVub/482-retire-panopticon

### CODE REVIEW

**Comment by jennyd** [comment]
🎉 🍰 💯 :pancakes: ☂️ 🎫 🎊

**Comment by whoojemaflip** [comment]
:cake: :cake: :cake:

**Comment by tijmenb** [comment]
Goodbye, old friend.

**Comment by rjw1** [comment]
woot! :1st_place_medal:

**Comment by alexmuller** [comment]
omg yay

**Pull request merged**
