### PR TITLE
Change host alerting priority

### PR DESCRIPTION
**Pull request by dazahern**
We want to be alerted when single points of failure go down. Set the contact groups for a host. Defaults to high-priority.

Needs some 👀 on these changes please.

### CODE REVIEW

**Comment by surminus** [comment]
I think the code looks fine. Is there a reason we're flagging PostgreSQL standbys as urgent but not MySQL slaves?

**Comment by dazahern** [comment]
@surminus this is because we grep'd `govuk_safe_to_reboot::can_reboot: 'no'` and changed what was returned. @rjw1 mentioned we probably have a discussion about adding the PostgreSQL standbys though.

**Comment by deanwilson** [comment]
Can we add a description to the PR please? The code looks fine but I'm guessing a little as to the intent.

**Comment by dazahern** [comment]
@deanwilson, edited my PR message. Thanks

**Comment by surminus** [comment]
Personally I'm happy with this, shall we merge?

**Comment by dazahern** [comment]
ta

**Pull request merged**
