### PR TITLE
Install git from PPA

### PR DESCRIPTION
**Pull request by thomasleese**
This allows us to get a more recent version of git.

### CODE REVIEW

**Comment by surminus** [comment]
You could add it as a mirror to our aptly repo: https://github.com/alphagov/govuk-puppet/blob/master/modules/govuk/manifests/node/s_apt.pp#L35-L111

**Comment by thomasleese** [comment]
@surminus Thanks, I've had another go, I think this makes more sense now!

**Comment by thomasleese** [comment]
I'm not sure how to specify the version of git we want to install, or if we even need to do that.

**Comment by thomasleese** [comment]
No longer required.

**Pull request closed without merging**
