### PR TITLE
Upgrade elasticsearch for logs on integration

### PR DESCRIPTION
**Pull request by h-lame**
We want to test out upgrading to 1.7.x as a precursor to trying this on
staging and eventually production.

### CODE REVIEW

**Comment by h-lame** [comment]
Flagged as DNM because we need to disable puppet on the logs machines and roll this change out manually one by one to each server.

**Comment by alexmuller** [comment]
Good to merge whenever you want 👍

**Comment by alexmuller** [comment]
This should be a rolling upgrade: https://www.elastic.co/guide/en/elasticsearch/reference/1.7/setup-upgrade.html#rolling-upgrades

**Comment by h-lame** [comment]
We've disabled puppet on the 3 machines, so we're ready to merge.

**Pull request merged**
