### PR TITLE
[#108858698] Enable new Whitehall attachment processing

### PR DESCRIPTION
**Pull request by alexmuller**
We've tested this in integration and we believe it works as we expect.

This might be easier to review by adding `?w=1` to the URL to remove whitespace changes.

### CODE REVIEW

**Comment by surminus** [comment]
LGTM, very exciting :fireworks:

**Comment by alexmuller** [comment]
Pushed a commit for the CPU check.

**Comment by rjw1** [comment]
https://govuk.zendesk.com/agent/tickets/1229635 may have a bearing on this. So hold off for a while.

**Comment by alexmuller** [comment]
We've had a look at that and we think it's unrelated.

**Comment by mattbostock** [comment]
:+1: Nice work! :eggplant:

**Pull request merged**
