### PR TITLE
Errbit environment config for share-sale-publisher

### PR DESCRIPTION
**Pull request by bradwright**
Adds Errbit configuration so the app can report errors and deployments.

- [x] Merge deployment#878

### CODE REVIEW

**Comment by mattbostock** [comment]
The build is failing because `errbit_environment_name` is mandatory and isn't set in Hiera's `development.yaml` for the dev VM.

**Comment by bradwright** [comment]
@mattbostock turns out that's [globally defined](https://github.com/alphagov/govuk-puppet/blob/master/modules/govuk/manifests/deploy/config.pp#L87) - will remove.

**Comment by bradwright** [comment]
@mattbostock updated. Will see what the tests say.

**Comment by bradwright** [comment]
@mattbostock ready for re-review.

**Pull request merged**
