### PR TITLE
Define redis url for whitehall

### PR DESCRIPTION
**Pull request by mgrassotti**
https://trello.com/c/JQREOuvh/424-use-sidekiq-gem

Define environment constants for whitehall, in order to configure the
govuk_sidekiq gem properly.

### CODE REVIEW

**Comment by mgrassotti** [comment]
this is related to https://github.com/alphagov/whitehall/pull/2633

**Comment by alexmuller** [comment]
`redis_host` and `redis_port` will have to be added as parameters to the `govuk::apps::whitehall` class or they won't do anything, similar to the `govuk::apps::publishing_api` class.

**Comment by mgrassotti** [comment]
👍 thanks I hope it's ok now

**Comment by alexmuller** [comment]
I'm not sure this will work yet, the parameters are present but they're not being used to do anything.

**Comment by mgrassotti** [comment]
Well we are using them inside the govuk_sidekiq gem, so here they should just be set. Does this makes sense?

**Comment by alexmuller** [comment]
Sure, but this Puppet change isn't doing anything - the parameters on the Puppet class aren't being used to change any state on the whitehall machines. Do they need to set an environment variable?

**Comment by alexmuller** [comment]
Ah cool, so in that case you'll need something similar to what's been done in #4584

**Comment by mgrassotti** [comment]
👍 great thanks

**Pull request merged**
